service:
  debug: true
  serviceName: user
  httpPort: 8083
  rpcPort: 8183
  callServiceKey: garden
  etcdAddress:
    - 192.168.125.185:2379
  zipkinAddress: http://192.168.125.185:9411/api/v2/spans

config:
  redisAddress: 192.168.125.185:6379
  redisPassword:
  redisDb: 0