service:
  debug: true
  serviceName: user
  httpOut: false
  httpPort: 8083
  allowCors: false
  rpcOut: false
  rpcPort: 9003
  callKey: garden
  callRetry: 50/80/100
  etcdKey: garden
  etcdAddress:
    - 192.168.125.186:2379
  zipkinAddress: http://192.168.125.186:9411/api/v2/spans

config:
  mysql_open: false
  mysql_addr: "127.0.0.1:3306"
  mysql_user: "root"
  mysql_pass: "0825"
  mysql_dbname: "test"
  mysql_charset: "utf8mb4"
  mysql_parseTime: true
  mysql_connPool: 10

  redis_open: false
  redis_addr: "127.0.0.1:6379"
  redis_pass: "0825"
  redis_db: 0
