service:
  debug: true
  serviceName: user

  httpOut: false
  httpPort: 8083
  allowCors: false
  rpcOut: false
  rpcPort: 9003

  callKey: garden
  callRetry: 50/80/100

  etcdKey: garden
  etcdAddress:
    - 192.168.125.164:2379

  tracerDrive: jaeger
  jaegerAddress: 192.168.125.193:6831
  #zipkinAddress: http://192.168.125.193:9411/api/v2/spans

  pushGatewayAddress: 192.168.125.193:9091

config:
  #redis:
    #host: "127.0.0.1"
    #port: "6379"
    #pass: ""
    #db: 0
  #db:
    #drive: mysql
    #host: "127.0.0.1"
    #port: "3306"
    #user: "root"
    #pass: ""
    #dbname: "test"
    #charset: "utf8mb4"
    #parseTime: true
    #connPool: 10
