service:
  debug: true
  serviceName: user
  #serviceIp: 127.0.0.1

  httpOut: false
  httpPort: 8083
  allowCors: false
  rpcOut: false
  rpcPort: 9003

  callKey: garden
  callRetry: 50/80/100

  etcdKey: garden
  etcdAddress:
    - 192.168.125.194:2379

  tracerDrive: jaeger
  jaegerAddress: 192.168.125.194:6831
  #zipkinAddress: http://192.168.125.194:9411/api/v2/spans

  pushGatewayAddress: 192.168.125.194:9091

config:
  db:
    drive: mysql
    host: "127.0.0.1"
    port: "3306"
    user: "root"
    pass: "0825"
    dbname: "garden_example"
    charset: "utf8mb4"
    parseTime: true
    connPool: 10
  #redis:
    #host: "127.0.0.1"
    #port: "6379"
    #pass: ""
    #db: 0
