service:
  debug: true
  serviceName: user
  listenOut: false
  listenPort: 8083
  callKey: garden
  callRetry: 50/80/100
  etcdKey: garden
  etcdAddress:
    - 192.168.125.185:2379
  zipkinAddress: http://192.168.125.185:9411/api/v2/spans
  amqpAddress: amqp://guest:guest@192.168.125.185:5672

config:
