routes:
  user:
    login:
      type: api
      path: /login
      limiter: 5/100000
      fusing: 5/10000
    exists:
      type: rpc
      path: /exists
      limiter: 5/100000
      fusing: 5/10000
  pay:
    order:
      type: api
      path: /order
      limiter: 5/100000
      fusing: 5/10000