service:
  debug: true
  serviceName: user
  httpOut: false
  httpPort: 8081
  rpcOut: false
  rpcPort: 9001
  callKey: garden
  callRetry: 50/80/100
  etcdKey: garden
  etcdAddress:
    - 192.168.125.186:2379
  zipkinAddress: http://192.168.125.186:9411/api/v2/spans

config:
