service:
  debug: true
  serviceName: pay

  httpOut: false
  httpPort: 8082
  allowCors: false
  rpcOut: false
  rpcPort: 9002

  callKey: garden
  callRetry: 50/80/100

  etcdKey: garden
  etcdAddress:
    - 192.168.125.164:2379

  tracerDrive: jaeger
  jaegerAddress: 192.168.125.164:6831
  zipkinAddress: http://192.168.125.164:9411/api/v2/spans

config: