service:
  debug: true
  serviceName: pay
  #serviceIp: 127.0.0.1

  httpOut: false
  httpPort: 8082
  allowCors: false
  rpcOut: false
  rpcPort: 9002

  callKey: garden
  callRetry: 50/80/100

  etcdKey: garden
  etcdAddress:
    - 127.0.0.1:2379

  tracerDrive: jaeger
  jaegerAddress: 127.0.0.1:6831
  #zipkinAddress: http://127.0.0.1:9411/api/v2/spans

  pushGatewayAddress: 127.0.0.1:9091

config:
  db:
    drive: mysql
    host: "127.0.0.1"
    port: "3306"
    user: "root"
    pass: "0825"
    dbname: "garden_example"
    charset: "utf8mb4"
    parseTime: true
    connPool: 10
  #redis:
    #host: "127.0.0.1"
    #port: "6379"
    #pass: ""
    #db: 0
