service:
  Debug: true
  ServiceName: pay
  HttpPort: 8082
  RpcPort: 8182
  CallServiceKey: garden
  EtcdAddress:
    - 192.168.125.185:2379
  ZipkinAddress: http://192.168.125.185:9411/api/v2/spans

config: