service:
  debug: true
  serviceName: pay
  httpOut: false
  httpPort: 8082
  rpcOut: false
  rpcPort: 9002
  callKey: garden
  callRetry: 50/80/100
  etcdKey: garden
  etcdAddress:
    - 192.168.125.186:2379
  zipkinAddress: http://192.168.125.186:9411/api/v2/spans

config:
  mysql:
    addr: "127.0.0.1"
    user: "root"
    pass: "123456"
    db:   "test"
  number: 32
  str: "hello"
