#service call key
callServiceKey: "goms by panco"

#etcd address, cluster format: 127.0.0.1:2379|127.0.0.2:2379
etcdAddr: "192.168.125.181:2379"
#elasticsearch address
esAddr: "192.168.125.181:9200"

#services
services:
  user:
    #routes
    register: "/register"
    login: "/login"