service:
  debug: true
  serviceName: my-gateway

  httpOut: false
  httpPort: 8080
  allowCors: true
  rpcOut: false
  rpcPort: 9000

  callKey: garden
  callRetry: 20/30/50

  etcdKey: garden
  etcdAddress:
    - 127.0.0.1:2379

  tracerDrive: jaeger
  jaegerAddress: 127.0.0.1:6831
  #zipkinAddress: http://127.0.0.1:9411/api/v2/spans

config:
  #redis:
    #open: true
    #host: "127.0.0.1"
    #port: "6379"
    #pass: ""
    #db: 0
  #db:
    #open: true
    #drive: mysql
    #host: "127.0.0.1"
    #port: "3306"
    #user: "root"
    #pass: ""
    #dbname: "test"
    #charset: "utf8mb4"
    #parseTime: true
    #connPool: 10
