#service call key
callServiceKey: "goms by panco"

#etcd address, support cluster
etcdAddr:
  - "192.168.125.182:2379"

#elasticsearch address
esAddr: "http://192.168.125.182:9200"

#rabbitmq address
amqpAddr: "amqp://guest:guest@192.168.125.182:5672"

#services
services:
  user:
    #routes
    register: "/register"
    login: "/login"