service:
  debug: true
  serviceName: gateway
  httpPort: 8080
  rpcPort: 8180
  callServiceKey: garden
  etcdAddress:
    - 192.168.125.185:2379
  zipkinAddress: http://192.168.125.185:9411/api/v2/spans

config: