routes:
  user:
    login:
      type: out
      path: /login
      limiter: 5/10000
      fusing: 5/1000
    exists:
      type: in
      path: /exists
      limiter: 5/10000
      fusing: 5/1000
  pay:
    order:
      type: out
      path: /order
      limiter: 5/10000
      fusing: 5/1000